# Generated by Django 3.1.4 on 2021-12-14 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="address",
            name="town_city",
            field=models.CharField(max_length=150, verbose_name="Town/City"),
        ),
    ]
