# Generated by Django 3.1.4 on 2021-09-25 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_userbase_last_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userbase',
            old_name='first_name',
            new_name='full_name',
        ),
        migrations.RemoveField(
            model_name='userbase',
            name='last_name',
        ),
    ]
