# Generated by Django 3.1.4 on 2021-09-25 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20210925_1625'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userbase',
            name='user_name',
        ),
    ]
