# Generated by Django 3.1.4 on 2021-12-11 18:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("store", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="users_wishlist",
            field=models.ManyToManyField(
                blank=True, related_name="user_wishlist", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="producttype",
            name="name",
            field=models.CharField(
                help_text="Required",
                max_length=255,
                unique=True,
                verbose_name="Product Type",
            ),
        ),
    ]
